deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>="
  secret_access_key:
    secure: "Encypted <secret-access-key>="
  region: "us-east-1"
  app: "example-app-name"
  env: "example-app-environment"
  bucket_name: "the-target-S3-bucket"
  
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
install:
  -pip install -r requirements.txt

before_script:
  -python manage.py migrate
  -python manage.py collectstatic

script:
  -black --check .
  -flake8 .
  -coverage run --source=mysite_app, polls manage.py test

after_script:
  -coveralls

